# Docker Compose file version
version: "3.2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    #ports:
      #- "53:53/tcp"
      #- "53:53/udp"
      #- "67:67/udp"
      #- "7780:80/tcp"
      #- "7743:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      ServerIP: '192.168.1.10'
      WEB_PORT: 7780
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - '/volume1/Server/MediaServer/config/pihole/:/etc/pihole/'
       - '/volume1/Server/MediaServer/config/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
